const Quarter = Object.freeze({
    SUMMER: 0,
    SPRING: 1,
    WINTER: 2,
    FALL: 3,
});

const SubjectAreas = Object.freeze([
    ['ANTH', 'Anthropology'],
    ['ARBC', 'Arabic'],
    ['ARLC', 'Arabic Literature and Cultures'],
    ['ARC ', 'ARC'],
    ['ART ', 'Art'],
    ['AHS ', 'Art History'],
    ['AST ', 'Asian Studies'],
    ['BSWT', 'Basic Writing'],
    ['BCH ', 'Biochemistry'],
    ['BIEN', 'Bioengineering'],
    ['BIOL', 'Biology'],
    ['BMSC', 'Biomedical Sciences'],
    ['BPSC', 'Botany/Plant Science'],
    ['BUS ', 'Business'],
    ['CBNS', 'Cell Biology and Neuroscience'],
    ['CMDB', 'Cell, Molecular, and Developmental Biology'],
    ['CHFY', 'CHASS First Year Experience'],
    ['CEE ', 'Chemical and Environmental Engineering'],
    ['CHE ', 'Chemical Engineering'],
    ['CHEM', 'Chemistry'],
    ['CHN ', 'Chinese'],
    ['CLA ', 'Classical Studies'],
    ['CNAS', 'College of Natural &amp; Ag Sci'],
    ['CPAC', 'Comparative Ancient Civilizations'],
    ['CPLT', 'Comparative Literature'],
    ['CS  ', 'Computer Science'],
    ['CRWT', 'Creative Writing'],
    ['CWPA', 'Creative Writing &amp; Writing for the Performing Arts'],
    ['DNCE', 'Dance'],
    ['ECON', 'Economics'],
    ['EDUC', 'Education'],
    ['EE  ', 'Electrical Engineering'],
    ['ENGR', 'Engineering'],
    ['ENGL', 'English'],
    ['ENTM', 'Entomology'],
    ['ENVE', 'Environmental Engineering'],
    ['ENSC', 'Environmental Sciences'],
    ['ENTX', 'Environmental Toxicology'],
    ['ETST', 'Ethnic Studies'],
    ['EUR ', 'European Culture'],
    ['EEOB', 'Evolution, Ecology, &amp; Organismal Biology'],
    ['FIL ', 'Filipino'],
    ['FREN', 'French'],
    ['GDIV', 'GDIV'],
    ['GSST', 'Gender and Sexuality Studies'],
    ['GEN ', 'Genetics'],
    ['GEO ', 'Geosciences'],
    ['GER ', 'German'],
    ['GBST', 'Global Studies'],
    ['GRK ', 'Greek'],
    ['HIST', 'History'],
    ['HISE', 'History of Europe'],
    ['HISA', 'History of the Americas'],
    ['HNPG', 'Honors'],
    ['HASS', 'Humanities, Arts, and Social Sciences'],
    ['ITAL', 'Italian'],
    ['JPN ', 'Japanese'],
    ['KOR ', 'Korean'],
    ['LATN', 'Latin'],
    ['LNST', 'Latin American Studies'],
    ['LWSO', 'Law and Society'],
    ['LGBS', 'Lesbian, Gay, Bisexual Studies'],
    ['LING', 'Linguistics'],
    ['MGT ', 'Management'],
    ['MSE ', 'Materials Science and Engineering'],
    ['MATH', 'Mathematics'],
    ['MDCL', 'MDCL'],
    ['ME  ', 'Mechanical Engineering'],
    ['MCS ', 'Media and Cultural Studies '],
    ['MCBL', 'Microbiology'],
    ['MEIS', 'Middle East &amp; Islamic Studies '],
    ['MUS ', 'Music'],
    ['NASC', 'Natural and Agricultural Sciences'],
    ['NEM ', 'Nematology'],
    ['NRSC', 'Neuroscience'],
    ['PCST', 'Peace &amp; Conflict Studies'],
    ['PHIL', 'Philosophy'],
    ['PHYS', 'Physics &amp; Astronomy'],
    ['PLPA', 'Plant Pathology &amp; Microbiology'],
    ['POSC', 'Political Science'],
    ['PSYC', 'Psychology'],
    ['PBPL', 'Public Policy'],
    ['REC ', 'Recreation'],
    ['RLST', 'Religious Studies'],
    ['RUSN', 'Russian Studies'],
    ['SOC ', 'Sociology'],
    ['SWSC', 'Soil and Water Science'],
    ['SEAS', 'Southeast Asian Studies'],
    ['SPN ', 'Spanish'],
    ['STAT', 'Statistics'],
    ['TFDP', 'Theater, Film &amp; Digital Production'],
    ['URST', 'Urban Studies'],
    ['VNM ', 'Vietnamese'],
]);

const ClassType = Object.freeze([
    ['LEC', 'Lecture'],
    ['DIS', 'Discussion'],
    ['LAB', 'Laboratory'],
    ['LCA', 'Additional lecture'],
    ['CLN', 'Clinic'],
    ['COL', 'Colloquium'],
    ['CON', 'Consultation'],
    ['FLD', 'Field'],
    ['IND', 'Individualized STUDY'],
    ['INT', 'Internship'],
    ['MCE', 'Multiple course entry'],
    ['PRC', 'Practicum'],
    ['RES', 'Research'],
    ['SCR', 'Screening'],
    ['SEM', 'Seminar'],
    ['STU', 'Studio'],
    ['THE', 'Thesis'],
    ['TPA', 'Term paper'],
    ['TUT', 'Tutorial'],
    ['WRK', 'Workshop'],
    ['ACT', 'Activity'],
    ['DEM', 'Demonstration'],
    ['ODL', 'Online dis and listening'],
    ['W&S', 'Workshop & screening'],
]);

const Location = Object.freeze([
    ['ANDHL', 'A. Gary Anderson Hall (ANDHL)'],
    ['BOYHL', 'Alfred M. Boyce Hall (BOYHL)'],
    ['ARTS', 'Arts Building (ARTS)'],
    ['ATH', 'Athletics and Dance Building (ATH)'],
    ['BATCH', 'Batchelor Hall (BATCH)'],
    ['HOUSE', 'Botany Headhouses(greenhouses) (HOUSE)'],
    ['BRNHL', 'Bourns Hall (BRNHL)'],
    ['SURGE', 'Campus Surge (SURGE)'],
    ['INTN', 'CHASS Interdisciplinary Bldg-North (INTN)'],
    ['INTS', 'CHASS Interdisciplinary Bldg-South (INTS)'],
    ['CHEM', 'Chemical Sciences (CHEM)'],
    ['ENTOM', 'Entomology (ENTOM)'],
    ['ENTMU', 'Entomology Research Museum (ENTMU)'],
    ['GENOM', 'Genomics Building (GENOM)'],
    ['GEOL', 'Geology Building (GEOL)'],
    ['WAT', 'Gordan Watkins Hall (WAT)'],
    ['CHPHL', 'Homer D. Chapman Hall (CHPHL)'],
    ['HUMN', 'Humanities (HUMN)'],
    ['HMNSS', 'Humanities and Social Sciences (HMNSS)'],
    ['LFSC', 'Life Sciences Building (LFSC)'],
    ['MSE', 'Materials Science and Engineering (MSE)'],
    ['OLMH', 'Olmsted Hall (OLMH)'],
    ['ONLNE', 'Online (ONLNE)'],
    ['PHY', 'Physics (PHY)'],
    ['PRCE', 'Pierce Hall (PRCE)'],
    ['PSYCH', 'Psychology (PSYCH)'],
    ['SCLAB', 'Science Laboratories 1 (SCLAB)'],
    ['SPTH', 'Spieth Hall (SPTH)'],
    ['SPR', 'Sproul Hall (SPR)'],
    ['BARN', 'The Barn (BARN)'],
    ['TBA', 'To Be Announced (TBA)'],
    ['ULB', 'University Laboratory Building (ULB)'],
    ['UNLH', 'University Lecture Hall (UNLH)'],
    ['UV', 'University Village (UV)'],
    ['CHUNG', 'Winston Chung Hall (CHUNG)'],
]);

const BreadthCourse = Object.freeze([
    ['E-S-EC', ['COE', 'Social Sciences - Econ, Poli Sci']],
    ['E-S-AN', ['COE', 'Social Sciences - Anth, Psyc, Soc']],
    ['E-S-ADD', ['COE', 'Social Sciences - Additional']],
    ['E-N-PS', ['COE', 'Nat Sci &amp; Math - Phys Sci']],
    ['E-N-BS', ['COE', 'Nat Sci &amp; Math - Biol Sci']],
    ['E-N-ADD', ['COE', 'Nat Sci &amp; Math - Additional']],
    ['E-H-WH', ['COE', 'Humanities - World History']],
    ['E-H-FA', ['COE', 'Humanities - Fine Arts, Lit, Phil, Rel Studies']],
    ['E-H-ADD', ['COE', 'Humanities - Additional']],
    ['E-ETH', ['COE', 'Ethnicity']],
    ['E-ENGL', ['COE', 'English Composition']],
    ['N-S-ADD', ['CNAS', 'Social Sciences - Additional']],
    ['N-S', ['CNAS', 'Social Sciences']],
    ['N-N-PS', ['CNAS', 'Nat Sci &amp; Math - Phys Sci']],
    ['N-N-MA', ['CNAS', 'Nat Sci &amp; Math - Math, Stat, Comp Sci']],
    ['N-N-BS', ['CNAS', 'Nat Sci &amp; Math - Biological Sci']],
    ['N-N-ADD', ['CNAS', 'Nat Sci &amp; Math - Additional']],
    ['N-WH', ['CNAS', 'Humanities - World History']],
    ['N-H-RS', ['CNAS', 'Humanities - Religious Studies']],
    ['N-H-PH', ['CNAS', 'Humanities - Philosophy']],
    ['N-H-FA', ['CNAS', 'Humanities - Fine Arts']],
    ['N-H-ADD', ['CNAS', 'Humanities - Additional']],
    ['N-ETH', ['CNAS', 'Ethnicity']],
    ['N-ENGL', ['CNAS', 'English Composition']],
    ['N-H-WH', ['CNAS ', 'Humanities - World History']],
    ['N-H-LT', ['CNAS ', 'Humanities - Lit, Phil, Rel Studies']],
    ['H-S-EC', ['CHASS',S'ocial Sciences - Econ, Poli Sci']],
    ['H-S-AN', ['CHASS',S'ocial Sciences - Anth, Psyc, Soc']],
    ['H-S-ADD', ['CHASS',S'ocial Sciences - Additional']],
    ['H-H-WH', ['CHASS',H'umanities - World History']],
    ['H-H-LT', ['CHASS',H'umanities - Lit, Phil, Rel Studies']],
    ['H-H-FA', ['CHASS',H'umanities - Fine Arts']],
    ['H-H-ADD', ['CHASS',H'umanities - Additional']],
    ['H-N-PS', ['CHASS', 'Nat Sci &amp; Math - Phys Sci']],
    ['H-N-MA', ['CHASS', 'Nat Sci &amp; Math - Math, Stat, Comp Sci']],
    ['H-N-BS', ['CHASS', 'Nat Sci &amp; Math - Biol Sci']],
    ['H-N-ADD', ['CHASS', 'Nat Sci &amp; Math - Additional']],
    ['H-ETH', ['CHASS', 'Ethnicity']],
    ['H-ENGL', ['CHASS', 'English Composition']],
]);

const CourseStatus = Object.freeze({
    OPEN: 1,
    CLOSED: 2,
    CANCELLED: 3,
});

const CourseRange = Object.freeze([
    ['LGraduate', 'Lower Division', [0, 99]],
    ['UGraduate', 'Upper Division', [100, 199]],
    ['Graduate', 'Graduate', [200, 299]],
    ['PostDoc', 'Professional/Teaching', [300, 999]]
]);


